# Generated by Django 3.2.3 on 2021-05-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_post_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='interagir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
