# Generated by Django 3.2.3 on 2021-05-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_interagir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='interagir',
        ),
        migrations.AddField(
            model_name='post',
            name='nota',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, null=0),
            preserve_default=False,
        ),
    ]
