# Generated by Django 3.2.3 on 2021-05-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_post_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
