# Generated by Django 3.2.3 on 2021-05-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_post_nota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sub_title',
            new_name='criador',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='comentarios',
            new_name='sinopse',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
